### ISSUE TITLE
Refactor localization from `l10n` to `easy_localization`

### ISSUE THREAD

**Issue by esmaeil-ahmadipour** [pactus-project/pactus-gui#38]
## Overview
**Component/Feature:** Refactor localization from `l10n` to `easy_localization`.  
**Reason:** `l10n` lacks key-independent translation management, causing issues.

## Goals
- Replace `l10n` with `easy_localization`.
- Improve translation management and scalability.

## Proposed Changes
- Implement `easy_localization` instead of `l10n`.
- Update translation files and ensure compatibility.

## Potential Impact
- **Functionality Impact:** Localization keys may need updating, but no major impact expected.  
- **Tests:** Update or add tests for localization changes.
- **ci:** Update  ci  localization settings.

**Comment by PouriaMoradi021** [comment]
### 📊 Current Status:
**Progress**: 0%

- ✔️ Completed Tasks:
  - [ ] Task 1:  add easy localization package to project
  - [ ] Task 2:  add Json translation files for English/other langauge

### 🚧 Challenges/Blockers:
- Not identified

### 🛤️ Next Steps:
- Estimated time for completion: 1D

### ❓ Questions/Requests:

----

@esmaeil-ahmadipour

**Comment by esmaeil-ahmadipour** [comment]
### 📊 Current Status:
**Progress**: 100%
**Estimated time**: 4h

- ✔️ Completed Tasks:
  - [x] Task 1:  fix translation files for applications text in `es` & `fr`
  - [x] Task 2:  fix configurations for `EasyLocalization` in `main.dart` file
  - [x] Task 3:   fix: fix `applications` text in `SplashScreen` page
  - [x] Task 4:  rearrange and reformat codes and code-styles
  - [x] Task 5:  chore: update analyzer configuration to ignore generated files (Excluded `.g.dart` and `.freezed.dart` files from `flutter analyze` in `.analysis_options.yaml`.)
  - [x] Task 6:  update `ci` for checking assets & translation files

### 🚧 Challenges/Blockers:
- Not identified

### 🛤️ Next Steps:
- none

### ❓ Questions/Requests:

- none
----
